experiment: 
  name: xg_boost_gene_1
  description: "XG Boost with elasticnet for feature selection."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: xg_boost
  est_params: {tree_method: "hist", device: "cuda"}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: 
      model_config_learning_rate:
        type: loguniform
        min: 0.01
        max: 0.2
      model_config_n_estimators:
        type: randint
        min: 50
        max: 400
      model_conifg__max_depth:
        type: randint
        min: 2
        max: 10
      model_config__min_child_weight:
        type: uniform
        min: 1
        max: 9
      model_config__gamma:
        type: uniform
        min: 0.1
        max: 4.9
      model_config__colsample_bytree:
        type: uniform
        min: 0.6
        max: 0.4 # min+max must be the upper bound
      reg_lambda:
        type: loguniform
        min: 0.0001
        max: 10

    cv: 5 # WARNING: these settings are fixed in the GPU code and must be changed in the script itself
    scoring: "neg_mean_squared_error" # WARNING: these settings are fixed in the GPU code and must be changed in the script itself
