name: gene_expression
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
- absl-py=2.3.1
- aiohappyeyeballs=2.6.1
- aiohttp=3.13.2
- aiosignal=1.4.0
- antlr4-python3-runtime=4.9.3
- asttokens=3.0.1
- attrs=25.4.0
- captum=0.7.0
- certifi=2025.11.12
- charset-normalizer=3.4.4
- click=8.3.1
- comm=0.2.3
- contourpy=1.3.3
- cycler=0.12.1
- decorator=5.2.1
- docker-pycreds=0.4.0
- einops=0.7.0
- executing=2.2.1
- filelock=3.20.0
- fonttools=4.61.1
- frozenlist=1.8.0
- fsspec=2025.12.0
- gitdb=4.0.12
- GitPython=3.1.46
- grpcio=1.76.0
- idna=3.11
- ipython=9.8.0
- ipython_pygments_lexers=1.1.1
- ipywidgets=8.1.8
- jedi=0.19.2
- Jinja2=3.1.6
- joblib=1.5.3
- jupyterlab_widgets=3.0.16
- kaleido=0.2.1
- kiwisolver=1.4.9
- lightning-utilities=0.15.2
- Markdown=3.10
- markdown-it-py=4.0.0
- MarkupSafe=3.0.2
- matplotlib=3.10.8
- matplotlib-inline=0.2.1
- mdurl=0.1.2
- mpmath=1.3.0
- multidict=6.7.0
- networkx=3.6.1
- numpy=1.26.4
- nvidia-cublas-cu12=12.1.3.1-
- nvidia-cuda-cupti-cu12=12.1.105
- nvidia-cuda-nvrtc-cu12=12.1.105
- nvidia-cuda-runtime-cu12=12.1.105
- nvidia-cudnn-cu12=9.1.0.70
- nvidia-cufft-cu12=11.0.2.54
- nvidia-curand-cu12=10.3.2.106
- nvidia-cusolver-cu12=11.4.5.107
- nvidia-cusparse-cu12=12.1.0.106
- nvidia-nccl-cu12=2.21.5
- nvidia-nvjitlink-cu12=12.9.86
- nvidia-nvtx-cu12=12.1.105
- omegaconf=2.3.0
- packaging=25.0
- pandas=2.3.3
- parso=0.8.5
- pexpect=4.9.0
- pillow=12.0.0
- platformdirs=4.5.1
- plotly=5.24.1
- prompt_toolkit=3.0.52
- propcache=0.4.1
- protobuf=5.28.3
- psutil=7.2.1
- ptyprocess=0.7.0
- pure_eval=0.2.3
- Pygments=2.19.2
- pyparsing=3.3.1
- python-dateutil=2.9.0.post0
- pytorch-lightning=2.4.0
- pytorch-tabnet=4.1.0
- pytorch-tabular=1.1.1
- pytz=2025.2
- PyYAML=6.0.3
- requests=2.32.5
- rich=14.2.0
- scikit-learn=1.8.0
- scipy=1.16.3
- sentry-sdk=2.48.0
- setproctitle=1.3.7
- setuptools=70.2.0
- six=1.17.0
- smmap=5.0.2
- stack-data=0.6.3
- sympy=1.13.1
- tenacity=9.1.2
- tensorboard=2.20.0
- tensorboard-data-server=0.7.2
- threadpoolctl=3.6.0
- torch=2.5.1+cu121
- torchmetrics=1.5.2
- tqdm=4.67.1
- traitlets=5.14.3
- typing_extensions=4.15.0
- tzdata=2025.3
- urllib3=2.6.2
- wandb=0.18.7
- wcwidth=0.2.14
- Werkzeug=3.1.4
- widgetsnbextension=4.0.15
- yarl=1.22.0
