experiment: 
  name: lassolars_agg_gene_3
  description: "Feature agg for feature extraction + LassoLARS."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true 
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: lasso_lars
  est_params: {'max_iter': 5000}

tuning:
  tune: true
  tuning_config:
    param_distributions: 
      regressor__regressor__alpha: 
        type: "loguniform"
        min: 0.001 
        max: 30
      regressor__selector__estimator__n_clusters:
        type: randint
        min: 500
        max: 1000
    n_iter: 200
    scoring: "neg_root_mean_squared_error"