experiment: 
  name: lassolars/lassolars_agg_no_conn_gene_1
  description: "LassoLars with feature agglomeration but without connectivity."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: lasso_lars
  est_params: {'max_iter': 1000}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__alpha': [0.02, 0.04, 0.06, 0.08, 1],
    'regressor__selector__estimator__n_clusters': [400, 600, 800, 1000]}
    cv: 5
    scoring: "neg_mean_squared_error"