experiment: 
  name: rf_elasticnet_gene_1
  description: "Random forest with elasticnet as feature selection."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true 
  selector_name: scikitlearn_estimator
  selector_params: {}
  estimator_config: 
    name: elastic_net
    params: {"max_iter": 10000, "tol": 0.01}

estimator:
  name: random_forest
  est_params: {"n_estimators": 100}

tuning:
  tune: true
  tuning_config:
    param_distributions: 
      regressor__regressor__max_depth:
        type: randint
        min: 3
        max: 15
      regressor__regressor__min_samples_leaf:
        type: randint
        min: 1
        max: 20
      regressor__regressor__max_features:
        type: loguniform
        min: 0.1
        max: 1
      regressor__selector__estimator__alpha:
        max: 0.7
        min: 0.2
        type: loguniform
      regressor__selector__estimator__l1_ratio:
        max: 0.5
        min: 0.01
        type: loguniform  
      regressor__selector__threshold:
        type: categorical
        list: ["mean", 
        "median", 
        "0.5*mean",
         "0.5*median",
          "1.5*mean", 
          "1.5*median"]

      
    n_iter: 60
    scoring: "neg_root_mean_squared_error" 