experiment: 
  name: rf_gene_3
  description: "Random forest without feature selection."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: false

estimator:
  name: random_forest
  est_params: {"n_estimators": 100}

tuning:
  tune: true
  tuning_config:
    param_distributions: 
      regressor__regressor__max_depth:
        type: randint
        min: 3
        max: 15
      regressor__regressor__min_samples_leaf:
        type: randint
        min: 1
        max: 20
      regressor__regressor__max_features:
        type: loguniform
        min: 0.1
        max: 0.5
      
    n_iter: 60
    scoring: "neg_root_mean_squared_error" 