experiment:
  name: rf_lassolars_gene_1
  description: "Lassolars feature selection + RF regression."

data:
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: scikitlearn_estimator
  selector_params: {}

  estimator_config:
    name: lasso_lars
    params:
      max_iter: 5000

estimator:
  name: random_forest
  est_params:
    n_estimators: 500

tuning:
  tuning_config:
    param_grid:
      regressor__selector__estimator__alpha: [0.01, 0.03, 0.05, 0.1]
      regressor__selector__threshold: ["median", "0.5*median"]
      regressor__regressor__min_samples_leaf: [1, 5, 10]
      regressor__regressor__max_depth: [5, 10, 15]
      regressor__regressor__max_features: [50, 100]
    cv: 5
    scoring: "neg_mean_squared_error"
