experiment: 
  name: baseline_elasticnet_retune_2_gene_3
  description: "Controlled experiment using elastic net for establishing minimum performance."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: elastic_net
  est_params: {'max_iter': 10000, 'tol': 0.01}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__alpha': [0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6],
    'regressor__regressor__l1_ratio': [0.0005, 0.001, 0.005, 0.1, 0.05, 0.1, 0.2]}
    cv: 5
    scoring: "neg_mean_squared_error"