experiment:
  name: rf_fs_elasticnet_gene_2
  description: "Random Forest feature selection + ElasticNet regression."

data:
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: scikitlearn_estimator
  selector_params: {}

  estimator_config:
    name: random_forest
    params:
      n_estimators: 500
      max_features: 300
      max_depth: 20
      random_state: 42
      n_jobs: 2

estimator:
  name: elastic_net
  est_params:
    max_iter: 2000
    tol: 0.01

tuning:
  tuning_config:
    param_grid:
      regressor__selector__threshold: ["mean", 0.01]
      regressor__regressor__alpha: [0.01, 0.05, 0.1]
      regressor__regressor__l1_ratio: [0.2, 0.5, 0.8]
    cv: 5
    scoring: "neg_mean_squared_error"
