experiment: 
  name: elasticnet/elasticnet_pca_gene_3
  description: "PCA + Elasticnet."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true 
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: pca 
    params: {}

estimator:
  name: elastic_net
  est_params: {'max_iter': 10000, 'tol': 0.01}

tuning:
  tune: true
  tuning_config:
    param_distributions: 
      regressor__regressor__alpha: 
        type: "loguniform"
        min: 0.001
        max: 0.9
      regressor__regressor__l1_ratio:
        type: "loguniform"
        min: 0.001
        max: 0.9
      regressor__selector__estimator__n_components:
        type: randint
        min: 100
        max: 500
    n_iter: 120
    scoring: "neg_root_mean_squared_error"
