experiment: 
  name: elasticnet_no_log_gene_1
  description: "Elasticnet without log transform to check whether it helps."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: elastic_net
  est_params: {'max_iter': 10000, 'tol': 0.01}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__alpha': [0.001, 0.01, 0.1, 0.2, 0.3],
    'regressor__regressor__l1_ratio': [0.1, 0.5, 0.7, 0.8, 0.9]}
    cv: 5
    scoring: "neg_mean_squared_error"


evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_state: 7
  estimator: elastic_net
  eval_config: {}