experiment: 
  name: elasticnet_gene_1
  description: "Controlled experiment using elastic net for establishing minimum performance."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: elastic_net
  est_params: {'max_iter': 10000, 'tol': 0.01}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_distributions: 
      regressor__regressor__alpha: 
        type: "loguniform"
        min: 0.001
        max: 0.9
      regressor__regressor__l1_ratio:
        type: "loguniform"
        min: 0.001
        max: 0.9
    n_iter: 120
    scoring: "neg_root_mean_squared_error"