experiment:
  name: pca_elasticnet_gene_1
  description: "PCA feature extraction + ElasticNet regression."

data:
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params:
  estimator_config:
    name: pca
    params: {}

estimator:
  name: elastic_net
  est_params:
    max_iter: 1000
    tol: 0.01

tuning:
  tuning_config:
    param_grid:
      regressor__selector__estimator__n_components: [20, 50, 80, 100, 150]
      regressor__regressor__alpha: [0.01, 0.1, 1.0]
      regressor__regressor__l1_ratio: [0.1, 0.5, 0.9]
    cv: 5
    scoring: "neg_mean_squared_error"

