experiment: 
  name: example_experiment
  description: "Controlled experiment using elastic net for establishing minimum performance."

data: 
  file_name: gene_1.txt
  data_dir: data/raw
  preprocessed_dir: data/preprocessed/baseline_elasticnet

preprocessing:
  save_preprocessed: true
  x_scaling: 
    - scaler: StandardScaler
      params: {}
  y_scaling:
    - scaler: log2
      params: {}
    - scaler: StandardScaler
      params: {}
  feature_selection:
    apply: false 
    method: SelectWithSklearn
    estimator: elastic_net
    params: {}
    tuning:
      tune: false 
      tuner: gridsearch_cv
      scoring: "mean_squared_error"
      param_grid: {}
      cv_folds: 5


training:
  estimator: ElasticNet
  tune: true
  param_grid: {}
  cv: 5
  scoring: "neg_mean_squared_error"
  random_state: 42

evaluation:
  n_splits: 5
  random_states: [0, 1, 2, 3, 4]