experiment: 
  name: elasticnet_agg_gene_1
  description: "Elasticnet with feature agglomeration as feature extraction method with ward algorithm."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: xg_boost
  est_params: {tree_method: "hist", device: "cuda"}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'model_config__min_child_weight': [1, 5, 10],
    'model_config__max_depth': [4, 6, 10],
    'model_config__subsample': [0.8, 1],
    'model_config__gamma': [1, 5, 10],
    'selector_estimator_config__n_clusters': [500, 800]}
    cv: 5 # WARNING: these settings are fixed in the GPU code and must be changed in the script itself
    scoring: "neg_mean_squared_error" # WARNING: these settings are fixed in the GPU code and must be changed in the script itself


evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_state: 7
  estimator: elastic_net
  eval_config: {}