experiment: 
  name: gb_feature_selection_gene_3
  description: "Gradient boosting with feature selection via elastic net."

data: 
  file_name: gene_3.txt
  data_dir: data/raw
  preprocessed_dir: data/preprocessed/gradient_boost

preprocessing:
  save_preprocessed: true
  x_scaling: 
    - scaler: standard
      params: {}
  y_scaling:
    - scaler: log2
      params: {}
    - scaler: standard
      params: {}
  feature_selection:
    apply: true
    selector: sklearn_model
    estimator: elastic_net
    params:
      alpha: 0.5
      l1_ratio: 0.1
    tuning:
      tune: false
    

training:
  estimator: gradient_boost
  tune: true
  tuner: gridsearch_cv
  param_grid: {"learning_rate": [0.05, 0.1, 0.15, 0.2], 
  "n_estimators": [200, 400, 500], 
  "max_depth": [2, 4, 6, 8],
  "subsample": [0.3, 0.5, 0.7, 1.0]}
  cv: 5
  scoring: "neg_mean_squared_error"
  random_state: 42

evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_states: [8, 9, 10, 11, 12]