experiment: 
  name: gradient_boost_gene_2
  description: "Gradient boosting with tuning around pre-established hyperparams."

data: 
  file_name: gene_2.txt
  data_dir: data/raw
  preprocessed_dir: data/preprocessed/gradient_boost

preprocessing:
  save_preprocessed: true
  x_scaling: 
    - scaler: standard
      params: {}
  y_scaling:
    - scaler: log2
      params: {}
    - scaler: standard
      params: {}
  feature_selection:
    apply: false 

training:
  estimator: gradient_boost
  tune: true
  plot: true
  tuner: gridsearch_cv
  param_grid: {"learning_rate": [0.1, 0.15, 0.2], 
  "n_estimators": [200], 
  "max_depth": [1, 2, 3, 4]}
  cv: 5
  scoring: "neg_mean_squared_error"
  random_state: 42
  test_size: 0.3

evaluation:
  test_size: 0.3
  n_splits: 5
  random_states: [0, 1, 2, 3, 4]