experiment: 
  name: gradient_boost_gene_3
  description: "Gradient boost without feature selection."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: gradient_boost
  est_params: {}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {"regressor__regressor__learning_rate": [0.01, 0.1, 0.2], 
    "regressor__regressor__n_estimators": [20, 30, 50, 100, 200], 
    "regressor__regressor__max_depth": [2, 4, 6],
    "regressor__regressor__loss": ["squared_error", "huber"],
    "regressor__regressor__alpha": [0.5, 0.9],
    "regressor__regressor__subsample": [0.8, 1.0]}
    cv: 5
    scoring: "neg_mean_squared_error"


evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_state: 7
  estimator: elastic_net
  eval_config: {}