experiment: 
  name: lassolars/lassolars_agg_retune_gene_2
  description: "LassoLars with feature agglomeration."

data: 
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: lasso_lars
  est_params: {'max_iter': 1000}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__alpha': [0.5, 1, 2, 5, 10],
    'regressor__selector__estimator__n_clusters': [30, 50, 100, 150, 200]}
    cv: 5
    scoring: "neg_mean_squared_error"