experiment: 
  name: lassolars/lassolars_retune_2_gene_1
  description: "LassoLars without feture selection."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: lasso_lars
  est_params: {'max_iter': 1000}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__alpha': [0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]}
    cv: 5
    scoring: "neg_mean_squared_error"


evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_state: 7
  estimator: elastic_net
  eval_config: {}