experiment:
  name: pca_elasticnet_gene_3
  description: "PCA feature extraction + ElasticNet regression."

data:
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: pca
  selector_params:
    whiten: false

  estimator_config:
    name: elastic_net
    params: {}

estimator:
  name: elastic_net
  est_params:
    max_iter: 1500
    tol: 0.01

tuning:
  tuning_config:
    param_grid:
      regressor__selector__n_components: [100, 200, 300, 500]
      regressor__regressor__alpha: [0.05, 0.1, 0.5, 1.0]
      regressor__regressor__l1_ratio: [0.3, 0.6, 0.9]
    cv: 5
    scoring: "neg_mean_squared_error"

