experiment:
  name: pca_elasticnet_gene_2
  description: "PCA feature extraction + ElasticNet regression."

data:
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: pca
  selector_params:
    whiten: false

  estimator_config:
    name: elastic_net
    params: {}

estimator:
  name: elastic_net
  est_params:
    max_iter: 1000
    tol: 0.01

tuning:
  tuning_config:
    param_grid:
      regressor__selector__n_components: [20, 50, 100, 150]
      regressor__regressor__alpha: [0.01, 0.05, 0.1]
      regressor__regressor__l1_ratio: [0.2, 0.5, 0.8]
    cv: 5
    scoring: "neg_mean_squared_error"


