experiment: 
  name: random_forest/random_forest_r2_gene_1
  description: "Random Forest with r2 scoring instead of MSE."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: random_forest
  est_params: {}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {"regressor__regressor__max_features": [100, 200, 300], 
    "regressor__regressor__n_estimators": [500], 
    "regressor__regressor__max_depth": [4, 15, 20]}
    cv: 5
    scoring: "r2"


evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_state: 7
  estimator: elastic_net
  eval_config: {}