experiment: 
  name: rf_agg_gene_2
  description: "Random Forest with feature agglomeration as feature extraction method with ward algorithm."

data: 
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: random_forest
  est_params: {n_estimators: 700}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'model_config__max_depth': [10, 15, 20],
    'model_config_max_features': [50, 80, 100],
    'selector_estimator_config__n_clusters': [50, 100, 200],
    'min_samples_leaf': [5, 20, 30]}
    cv: 5 # WARNING: these settings are fixed in the GPU code and must be changed in the script itself
    scoring: "neg_mean_squared_error" # WARNING: these settings are fixed in the GPU code and must be changed in the script itself

