experiment:
  name: rf_fs_gene_2
  description: "Random Forest feature selection for gene 2."

data:
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: scikitlearn_estimator
  selector_params:
    threshold: ["mean", 0.01]

  estimator_config:
    name: random_forest
    params:
      n_estimators: 300
      max_depth: 10
      random_state: 42
      n_jobs: -1

estimator:
  name: random_forest
  est_params: {}

tuning:
  tuning_config:
    param_grid:
      regressor__selector__threshold: ["mean", 0.005, 0.01]
      regressor__selector__estimator__n_estimators: [200, 300]
      regressor__selector__estimator__max_features: ["sqrt", 0.5]
    cv: 5
    scoring: "neg_mean_squared_error"
