experiment:
  name: rf_fs_gene_3
  description: "Random Forest feature selection for gene 3."

data:
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: scikitlearn_estimator
  selector_params:
    threshold: ["median", 0.02, 0.05]

  estimator_config:
    name: random_forest
    params:
      n_estimators: 700
      max_depth: 20
      random_state: 42
      n_jobs: -1

estimator:
  name: random_forest
  est_params: {}

tuning:
  tuning_config:
    param_grid:
      regressor__selector__threshold: ["median", 0.01, 0.02, 0.05]
      regressor__selector__estimator__n_estimators: [500, 700]
      regressor__selector__estimator__max_features: ["sqrt", 0.33]
    cv: 5
    scoring: "neg_mean_squared_error"

