experiment:
  name: rf_fs_elasticnet_gene_3
  description: "Random Forest feature selection + ElasticNet regression."

data:
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling:
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}

feature_selection:
  apply: true
  selector_name: scikitlearn_estimator
  selector_params: {}

  estimator_config:
    name: random_forest
    params:
      n_estimators: 500
      max_depth: 15
      max_features: 300
      min_samples_leaf: 5
      random_state: 42
      n_jobs: -1

estimator:
  name: elastic_net
  est_params:
    max_iter: 5000
    tol: 0.001

tuning:
  tuning_config:
    param_grid:
      regressor__selector__threshold: ["median", 0.01, 0.02]
      regressor__regressor__alpha: [0.05, 0.1, 0.5, 1.0]
      regressor__regressor__l1_ratio: [0.3, 0.6, 0.9]
    cv: 5
    scoring: "neg_mean_squared_error"
