experiment: 
  name: twostep/rf_svr_gene_3
  description: "Two step model using RF for classification and svr for regression."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : balanced_rf
    classifier_params: {"n_estimators": 300}
    regressor_name: svr
    regressor_params: {"max_iter": 5000}
tuning:
  tune: true
  tuning_config:
    param_distributions:  
      regressor__regressor__regressor__C:
        type: loguniform
        min: 0.1
        max: 10
      regressor__regressor__regressor__kernel: 
        type: categorical
        list: ['rbf', 'poly']
      regressor__regressor__regressor__gamma: 
        type: loguniform
        min: 0.0001
        max: 10
      regressor__regressor__regressor__epsilon:
        max: 10
        min: 0.001
        type: loguniform
      regressor__regressor__classifier__max_depth:
        type: randint
        min: 3
        max: 20
      regressor__regressor__classifier__min_samples_leaf:
        type: randint
        min: 1
        max: 20
      regressor__regressor__classifier__max_features:
        type: loguniform
        min: 0.1
        max: 1  
    n_iter: 60
    scoring: "neg_root_mean_squared_error"