experiment: 
  name: test_transformer
  description: "Just for testing whether code refactor runs smoothly."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: None
  y_scaling: log2
  x_scaler_params: {}
  y_scaler_params: {}


feature_selection:
  apply: false
  selector: sklearn_model
  estimator: elastic_net
  tuning:
    tune: false
  params: {"alpha": 0.3,
"l1_ratio": 0.1}

estimator:
  name: tabtransformer
  est_params: {"model_params__task": "regression",
  "trainer_params__max_epochs": 200,
  "optimizer_params__optimizer": "Adam",
  "model_params__transformer_activation": "LeakyReLU"}

tuning:
  param_grid: {"model_params__learning_rate": [0.00001, 0.0001, 0.001, 0.01],
  "model_params__embedding_dropout": [0.1, 0.2],
  "model_params__num_attn_blocks": [2, 3, 4],
  "trainer_params__batch_size": [32, 64],
  "model_params__ff_hidden_multiplier": [2, 4, 6]}

evaluation:
  plot: true
  test_size: 0.3
  n_splits: 5
  random_state: 7
  estimator: tab_transformer
  eval_config: {}