experiment: 
  name: transformer/transformer_agg_gene_1
  description: "Transformer with feature agglomeration."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: None
  y_scaling: log2
  x_scaler_params: {}
  y_scaler_params: {}


feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: tabtransformer
  est_params: {"model_params__task": "regression",
  "trainer_params__max_epochs": 200,
  "optimizer_params__optimizer": "Adam",
  "trainer_params__batch_size": 8,
  "model_params__input_embed_dim": 12,
  "model_params__num_heads": 2}

tuning:
  param_grid: {"model_config__model_params__learning_rate": [0.0001, 0.001],
  "model_config__model_params__num_attn_blocks": [2, 3],
  "model_config__model_params__transformer_activation": ["LeakyReLU", "GEGLU"],
  "selector_estimator_config__n_clusters": [600, 800]}
