data:
  data_dir: data/raw
  file_name: gene_1.txt
  preprocessed_dir: data/preprocessed/baseline_elasticnet

experiment:
  description: Testing transformer training/tuning
  name: transformer_test_gene_1


preprocessing:
  feature_selection:
    apply: false
  save_preprocessed: true
  x_scaling:
  - params: {}
    scaler: standard
  y_scaling:
  - params: {}
    scaler: log2
  - params: {}
    scaler: standard
training:
  cv: 5
  estimator: transformer
  param_grid: {"optimizer_config__optimizer": ["Adam"],
    "model_config__learning_rate": [0.000005, 0.00001, 0.00005],
    "model_config__num_attn_blocks": [8],
    "model_config__ff_hidden_multiplier": [4],
    "model_config__transformer_activation": ["LeakyReLU"],
    "model_config__embedding_dropout": [0.1]}
  scoring: MeanSquaredError
  tune: true
  tuner: gridsearch_cv


evaluation:
  plot: true
  n_splits: 5
  random_states:
  - 0
  - 1
  - 2
  - 3
  - 4
  test_size: 0.3

