experiment: 
  name: twostep/twostep_agg_adaboost_lassolars_retune_gene_1
  description: "Two step model using feature aggregation for feature extraction, ada boost for classification and lassolars for regression."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: hierarchical
  est_params: 
    classifier_name : balanced_ada_boost
    classifier_params: {}
    regressor_name: lasso_lars
    regressor_params: 
      max_iter: 5000

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__classifier__n_estimators': [50, 100, 200],
    'regressor__regressor__classifier__learning_rate': [0.3, 0.5, 1],
    'regressor__regressor__regressor__alpha': [0.005, 0.01, 0.02, 0.05],
    'regressor__selector__estimator__n_clusters': [300, 400, 500]}
    cv: 5
    scoring: "neg_mean_squared_error"