experiment: 
  name: svr_agg_gene_3
  description: "Controlled experiment using elastic net for establishing minimum performance."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true 
  selector_name: scikitlearn_transformation
  selector_params: {}
  estimator_config: 
    name: feature_agg 
    params: {}

estimator:
  name: svr
  est_params: {'tol': 0.001}

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_distributions: 
      regressor__regressor__C:
        type: loguniform
        min: 0.1
        max: 10
      regressor__regressor__kernel: 
        type: categorical
        list: ['rbf', 'poly']
      regressor__regressor__gamma: 
        type: loguniform
        min: 0.0001
        max: 10
      regressor__regressor__epsilon: 
        type: loguniform
        min: 0.001
        max: 10
      regressor__selector__estimator__n_clusters:
        type: randint
        min: 500
        max: 1000
    n_iter: 200
    scoring: "neg_root_mean_squared_error"
