experiment: 
  name: twostep/svc_xgb_gene_1
  description: "Two step model using svc for class. and XGBoost for regression."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : svc
    classifier_params: {"class_weight": "balanced"}
    regressor_name: xg_boost
    regressor_params: {tree_method: "hist", device: "cpu", n_jobs: 1}
tuning:
  tune: true
  tuning_config:
    param_distributions:  
      regressor__regressor__classifier__C:
        type: loguniform
        min: 0.1
        max: 10
      regressor__regressor__classifier__kernel: 
        type: categorical
        list: ['rbf', 'poly']
      regressor__regressor__classifier__gamma: 
        type: loguniform
        min: 0.0001
        max: 10
      regressor__regressor__regressor__learning_rate:
        type: loguniform
        min: 0.01
        max: 0.2
      regressor__regressor__regressor__n_estimators:
        type: randint
        min: 50
        max: 400
      regressor__regressor__regressor__max_depth:
        type: randint
        min: 2
        max: 10
      regressor__regressor__regressor__min_child_weight:
        type: uniform
        min: 1
        max: 9
      regressor__regressor__regressor__gamma:
        type: uniform
        min: 0.1
        max: 4.9
      regressor__regressor__regressor__colsample_bytree:
        type: uniform
        min: 0.6
        max: 0.4 # min+max must be the upper bound
      regressor__regressor__regressor__reg_lambda:
        type: loguniform
        min: 0.0001
        max: 1 
      regressor__regressor__regressor__reg_alpha:
        type: loguniform
        min: 0.01
        max: 50

    n_iter: 60
    scoring: "neg_root_mean_squared_error"