experiment: 
  name: twostep/svc_rf_lassolars_gene_2
  description: "Two step model using svc for class. and RF for regression + lassolars for feature selection."

data: 
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: true
  estimator_config:
    name: lasso_lars
    params:
      max_iter: 5000
  selector_name: scikitlearn_estimator
  selector_params: {}

estimator:
  name: hierarchical
  est_params: 
    classifier_name : svc
    classifier_params: {"class_weight": "balanced"}
    regressor_name: random_forest
    regressor_params: {"n_estimators": 300}
tuning:
  tune: true
  tuning_config:
    param_distributions: 
      regressor__regressor__classifier__C:
        type: loguniform
        min: 0.1
        max: 10
      regressor__regressor__classifier__kernel: 
        type: categorical
        list: ['rbf', 'poly']
      regressor__regressor__classifier__gamma: 
        type: loguniform
        min: 0.0001
        max: 10
      regressor__regressor__regressor__max_depth:
        type: randint
        min: 3
        max: 20
      regressor__regressor__regressor__min_samples_leaf:
        type: randint
        min: 1
        max: 20
      regressor__regressor__regressor__max_features:
        type: loguniform
        min: 0.1
        max: 1  
      regressor__selector__estimator__alpha:
        max: 0.3
        min: 0.001
        type: loguniform
      regressor__selector__threshold:
        list:
        - mean
        - median
        - 0.5*mean
        - 0.5*median
        - 1.5*mean
        - 1.5*median
        type: categorical

    n_iter: 60
    scoring: "neg_root_mean_squared_error"