experiment: 
  name: twostep/svc_rf_gene_1
  description: "Two step model using svc for class. and RF for regression."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : svc
    classifier_params: {"class_weight": "balanced"}
    regressor_name: random_forest
    regressor_params: {"n_estimators": 300}
tuning:
  tune: true
  tuning_config:
    param_distributions:  
      regressor__regressor__classifier__C:
        type: loguniform
        min: 0.1
        max: 10
      regressor__regressor__classifier__kernel: 
        type: categorical
        list: ['rbf', 'poly']
      regressor__regressor__classifier__gamma: 
        type: loguniform
        min: 0.0001
        max: 10
      regressor__regressor__regressor__max_depth:
        type: randint
        min: 3
        max: 20
      regressor__regressor__regressor__min_samples_leaf:
        type: randint
        min: 1
        max: 20
      regressor__regressor__regressor__max_features:
        type: loguniform
        min: 0.1
        max: 1  

    n_iter: 120
    scoring: "neg_root_mean_squared_error"