experiment: 
  name: twostep/twostep_adaboost_rf_gene_2
  description: "Two step model using random forest for classification and RF for regression."

data: 
  file_name: gene_2.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : balanced_ada_boost
    classifier_params:
      n_estimators: 500
    regressor_name: random_forest
    regressor_params: {"n_estimators": 500}
tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__classifier__n_estimators': [50, 100, 200, 300],
    'regressor__regressor__classifier__learning_rate': [0.01, 0.1, 0.3, 0.5],
    'regressor__regressor__regressor__max_depth': [5, 10, 15],
    'regressor__regressor__regressor__max_features': [50, 100, 200]
    }
    cv: 5
    scoring: "neg_mean_squared_error"
