experiment: 
  name: twostep/twostep_svc_rf_gene_3
  description: "Two step model using svc for class. and RF for regression."

data: 
  file_name: gene_3.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2 # no standard scaling because then we cant generate classifier labels via y>0s
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : svc
    classifier_params: {}
    regressor_name: random_forest
    regressor_params: {"n_estimators": 500, "n_bins": 32}
tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__classifier__C': [1, 5, 10, 15, 20],
    'regressor__regressor__regressor__max_depth': [15, 20, 25],
    'regressor__regressor__regressor__max_features': [400, 600, 800, 1000]
    }
    cv: 5
    scoring: "neg_mean_squared_error"
