experiment: 
  name: twostep/twostep_rf_lassolars_gene_1
  description: "Two step model using random forest for classification and elasticnet for regression."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
    - standard
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : balanced_rf
    classifier_params:
      n_estimators: 500
    regressor_name: lasso_lars
    regressor_params: 
      max_iter: 1000

tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__classifier__max_depth': [10, 12, 15, 18],
    'regressor__regressor__classifier__max_features': ["sqrt", 200],
    'regressor__regressor__regressor__alpha': [0.01, 0.1, 0.2, 0.5]}
    cv: 5
    scoring: "neg_mean_squared_error"
