experiment: 
  name: twostep/twostep_svc_rf_gene_1
  description: "Two step model using svc for class. and RF for regression."

data: 
  file_name: gene_1.txt
  data_dir: data/raw

preprocessing:
  x_scaling: 
    - standard
  y_scaling:
    - log2
  x_scaler_params: {}
  y_scaler_params: {}
feature_selection:
  apply: false 

estimator:
  name: hierarchical
  est_params: 
    classifier_name : svc
    classifier_params: {}
    regressor_name: random_forest
    regressor_params: {"n_estimators": 500}
tuning:
  tune: true
  tuner: gridsearch_cv
  tuning_config:
    param_grid: {
    'regressor__regressor__classifier__C': [0.5, 1, 5, 10],
    'regressor__regressor__regressor__max_depth': [5, 10, 15, 20],
    'regressor__regressor__regressor__max_features': [50, 100, 200, 300, 400]
    }
    cv: 5
    scoring: "neg_mean_squared_error"
